[world]
kind = "WorldContract"
class_hash = "0x6bd5e2d06cb841c424d2b61ee28610fb33eb90a6ba9e8cd9a85302e59c16fd9"
original_class_hash = "0x6bd5e2d06cb841c424d2b61ee28610fb33eb90a6ba9e8cd9a85302e59c16fd9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x67477278539cb28c0602e9ebd471b8e7a2bb4416708cfa9858adb3ac13b066e"
transaction_hash = "0x72b238b61e63070f402fdb42e5724647f964d477863ad88e2364c13fbcdf695"
block_number = 3
seed = "mateo-saya-v010"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://starknet-sepolia.g.alchemy.com/v2/PovJ0plog8O9RxyaPMYAZiKHqZ5LLII_"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x6a251a3725dc80516156b4ceaca440d294f288899facaa504d5656a7c175ad1"
class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
original_class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples_actions_actions.json"
reads = []
writes = [
    "Moves",
    "Position",
]
computed = []
name = "dojo_examples::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x5508ab47983d4842a780fe483cb9ba5d24ad4b8d0196f767cd5983398b9f4c4"
original_class_hash = "0x5508ab47983d4842a780fe483cb9ba5d24ad4b8d0196f767cd5983398b9f4c4"
abi = "manifests/dev/abis/deployments/models/dojo_examples_actions_actions_moved.json"
name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3c690e6a69960642e2e276299c04ee4eb57f8dabb0f59dc96b09faf39c82a9"
original_class_hash = "0x3c690e6a69960642e2e276299c04ee4eb57f8dabb0f59dc96b09faf39c82a9"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_emote_message.json"
name = "dojo_examples::models::emote_message"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "emote"
type = "Emote"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6eeffc6c72945b6ef419d3c67ed377408437782fdc41fa7a52339cd30d6c563"
original_class_hash = "0x6eeffc6c72945b6ef419d3c67ed377408437782fdc41fa7a52339cd30d6c563"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_moves.json"
name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x74e835af876c9f95977537b91d60d656f6ff2a4a8b2bb8d47448f345980f612"
original_class_hash = "0x74e835af876c9f95977537b91d60d656f6ff2a4a8b2bb8d47448f345980f612"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_player_config.json"
name = "dojo_examples::models::player_config"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3c3632f38ab3ba550bd3c596e2af55002d43bc76b7b660a3a57b49795307c58"
original_class_hash = "0x3c3632f38ab3ba550bd3c596e2af55002d43bc76b7b660a3a57b49795307c58"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_position.json"
name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
