[world]
kind = "WorldContract"
class_hash = "0x6ceaf14e9f17e51b13d205f8d55913ea03a7534b7a067cb941adf2e577868e3"
original_class_hash = "0x6ceaf14e9f17e51b13d205f8d55913ea03a7534b7a067cb941adf2e577868e3"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x6294528d1139adb3bd42e831693e41d740dbd206b43ce956661a3b323c5bf2b"
transaction_hash = "0x71f62320aba0cedd68ba8ca7114d9344edf647c2ecacc62307d479954d3e34b"
block_number = 3
seed = "mateo-saya-v017"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://starknet-sepolia.g.alchemy.com/v2/PovJ0plog8O9RxyaPMYAZiKHqZ5LLII_"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x30e8703bfba22146517edc6ac46ab884890c98506a0df84301b23dfef2afc4c"
class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
original_class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples_actions_actions.json"
reads = []
writes = [
    "Moves",
    "Position",
]
computed = []
name = "dojo_examples::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x91e05e8691a82229a17cf2b9b01b6f339fe704550151786b65734f0a9e45f1"
original_class_hash = "0x91e05e8691a82229a17cf2b9b01b6f339fe704550151786b65734f0a9e45f1"
abi = "manifests/dev/abis/deployments/models/dojo_examples_actions_actions_moved.json"
name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1080134c112da75344e02e4a6a9629778f5b7c0bf3f81055f1304bf75acaf75"
original_class_hash = "0x1080134c112da75344e02e4a6a9629778f5b7c0bf3f81055f1304bf75acaf75"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_emote_message.json"
name = "dojo_examples::models::emote_message"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "emote"
type = "Emote"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e9c87df132573ed64a84b5d18059ba86cabef0ae0a4ccd211ce90ecb3dfce3"
original_class_hash = "0x2e9c87df132573ed64a84b5d18059ba86cabef0ae0a4ccd211ce90ecb3dfce3"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_moves.json"
name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x151d4e1655053bc12c41f2e46ff6cb740c024320f129d92331cb1d2e59e4aa3"
original_class_hash = "0x151d4e1655053bc12c41f2e46ff6cb740c024320f129d92331cb1d2e59e4aa3"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_position.json"
name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
